cononaplane/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('base.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
    path('log/', include('log.urls',  namespace='log')),
    path('lost_and_found/', include('lost_and_found.urls', namespace="lost_and_found")),
]

log/urls.py
from django.urls import path

from . import views

app_name = 'log'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index', kwargs={"status": "active"}),
    path('<str:status>', views.IndexView.as_view(), name='index'),
    path('threads', views.ThreadsView.as_view(), name='threads', kwargs={"status": "active"}),
    path('threads/<int:pk>', views.ThreadDetailView.as_view(), name="show"),
    path('threads/<str:status>', views.ThreadsView.as_view(), name='threads'),
    path('entries/new', views.ThreadFormView.as_view(), name='create'),
    path('entries/<int:pk>/update', views.ThreadFormView.as_view(), name='update')
]

lost_and_found/urls.py
from django.urls import path, re_path

from . import views

app_name = "lost_and_found"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("search/<str:status>", views.SearchFormView.as_view(), name="search"),
    path("results/<str:status>", views.SearchResultsView.as_view(), name="results"),
    path("inventory", views.InventoryView.as_view(), name="inventory"),
    path("detail/<pk>", views.ItemView.as_view(), name="detail"),
    path("new/<str:status>", views.NewItemView.as_view(), name="new"),
    path("edit/<pk>", views.UpdateItemView.as_view(), name="edit"),
]

lost_and_found/models.py
from django.conf import settings
from django.contrib.postgres.indexes import GinIndex
from django.db import models

from model_utils.models import TimeStampedModel as TSModel
from simple_history.models import HistoricalRecords

from base.models import Convention


class Category(TSModel):
    name = models.CharField(max_length=60, unique=True)
    in_use = models.BooleanField(default=True)

    def __str__(self) -> str:
        if self.in_use:
            return self.name
        else:
            return f"{self.name} (not in use)"


class Item(TSModel):
    STATUSES = {"found", "inventoried", "missing", "returned"}
    found = models.BooleanField(default=False, db_index=True)
    inventoried = models.BooleanField(default=False, db_index=True)
    missing = models.BooleanField(default=False, db_index=True)
    returned = models.BooleanField(default=False, db_index=True)

    where_found = models.CharField(max_length=200, null=True, blank=True)
    where_last_seen = models.CharField(max_length=200, null=True, blank=True)

    description = models.CharField(max_length=200)
    details = models.TextField()

    owner_contact = models.CharField(max_length=200, null=True, blank=True)
    owner_name = models.CharField(max_length=200, null=True, blank=True)
    who_claimed = models.CharField(max_length=200, null=True, blank=True)

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING)
    rolename = models.CharField(max_length=25)

    category = models.ForeignKey(Category, on_delete=models.DO_NOTHING)
    convention = models.ForeignKey(Convention, on_delete=models.DO_NOTHING)

    history = HistoricalRecords()

    @property
    def status(self) -> str:
        if self.returned:
            return "returned"
        if self.inventoried:
            return "inventoried"
        if self.found:
            return "found"
        if self.missing:
            return "missing"
        return "WTH"

    @status.setter
    def status(self, val: str) -> str:
        if val == "returned":
            self.returned = True
        if val == "inventoried":
            self.inventoried = True
        if val == "found":
            self.found = True
        if val == "missing":
            self.missing = True
        return val

    def clean(self) -> None:
        return super().clean()

    class Meta:
        indexes = [
            GinIndex(fields=['description', 'details'])
        ]
        ordering = ["created"]
        permissions = [(
            "can_inventory",
            "Can perform inventory functions"
        )]

lost_and_found/forms.py
from typing import Any, Dict, List, Type
from django.forms import CharField, CheckboxSelectMultiple, ChoiceField, Form, HiddenInput, IntegerField, \
    ModelChoiceField, ModelForm, ModelMultipleChoiceField, RadioSelect

from base.models import Convention
from .models import Category, Item


class SearchForm(Form):
    SEARCH_TYPES = (
        ("all", "Find All"),
        ("any", "Find Any"),
        ("phrase", "Find Exact Phrase"),
        ("websearch", "Advanced Query")
    )

    template_name = "lost_and_found/_search_form.html"

    convention = ModelChoiceField(queryset=Convention.objects.all())
    categories = ModelMultipleChoiceField(queryset=Category.objects.filter(in_use=True),
                                          widget=CheckboxSelectMultiple)
    keywords = CharField(max_length=200, required=False)
    search_type = ChoiceField(choices=SEARCH_TYPES,
                              widget=RadioSelect)

    def __init__(self, *args, **kwargs) -> None:
        super().__init__(*args, **kwargs)
        self.fields["convention"].initial = Convention.current


class ItemForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(ItemForm, self).__init__(*args, **kwargs)

    @property
    def missing(self) -> bool:
        return self.instance and self.instance.missing

    @property
    def found(self) -> bool:
        return self.instance and self.instance.found

    @property
    def returned(self) -> bool:
        return self.instance and self.instance.returned

    class Meta:
        model: Type = Item
        fields = [
            "category",
            "description",
            "where_last_seen",
            "owner_name",
            "owner_contact",
            "where_found",
            "who_claimed",
            "missing",
            "found",
            "returned",
            "inventoried"
        ]
        widgets: dict = {
            "missing": HiddenInput,
            "found": HiddenInput,
            "returned": HiddenInput,
            "inventoried": HiddenInput
        }

        @property
        def asdf(self) -> list:
            fields = ["category", "description"]
            if self.missing:
                fields += ["where_last_seen", "owner_name", "owner_contact"]
            if self.found:
                fields += ["where_found"]
            if self.returned:
                fields += ["who_claimed"]

            fields += ["details"]
            return fields


class JumpForm(Form):
    jump = IntegerField(min_value=1)

    def clean(self) -> Dict[str, Any]:
        cleaned_data = super().clean()
        pk = cleaned_data.get('jump')

        if pk:
            try:
                Item.objects.get(pk=pk)
            except Item.DoesNotExist:
                self.add_error('jump', 'No such item')
        return cleaned_data

lost_and_found/views.py
from typing import Any, Dict, Type

from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib.postgres.search import SearchQuery, SearchVector
from django.db import transaction
from django.db.models import QuerySet
from django.forms.models import BaseModelForm
from django.http import HttpRequest, HttpResponse
from django.shortcuts import redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import TemplateView, FormView, ListView, DetailView
from django.views.generic.edit import ModelFormMixin, CreateView, UpdateView

from base.models import Convention

from .forms import JumpForm, SearchForm
from .models import Item


class IndexView(PermissionRequiredMixin, TemplateView):
    """
    Implement the Lost and Found Splash Page, which begins the choose-your-adventure
    by presenting two paths: is the item being REPORTED MISSING, or REPORTED FOUND?

    This leads to the SearchFormView, always, never directly to creation.
    """
    template_name: str = "lost_and_found/index.html"
    permission_required = ("lost_and_found.view_item",)

    def get_context_data(self, **kwargs) -> Dict[str, Any]:
        context: Dict[str, Any] = super().get_context_data(**kwargs)
        context["jump_form"] = JumpForm()
        self.request.session["inventory"] = False
        return context

    def get(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse:
        if "jump" in request.GET:
            return redirect(reverse_lazy("lost_and_found:detail", args=(request.GET['jump'],)))
        return super().get(request, *args, **kwargs)


class SearchFormView(PermissionRequiredMixin, FormView):
    """
    By default, searches items reported missing or reported found by category, description, details.

    Always displayed before permitting a user to create a new item, to reduce the likelihood
    of duplicates.

    Colour coded for adventure path (missing vs found)
    """
    template_name: str = "lost_and_found/search.html"
    permission_required = ("lost_and_found.view_item",)
    form_class = SearchForm

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context["body_bg"] = self.kwargs["status"]
        context["jump_form"] = JumpForm()
        return context

    def get_success_url(self) -> str:
        return reverse_lazy("lost_and_found:results", args=self.args, kwargs=self.kwargs)

    def post(self, request: HttpRequest, *args, **kwargs) -> HttpResponse:
        with transaction.atomic():
            redir = self.get_success_url()
            qd = request.POST.copy()
            if "csrfmiddlewaretoken" in qd:
                qd.pop("csrfmiddlewaretoken")
            return redirect(redir + "?" + qd.urlencode())


class SearchResultsView(PermissionRequiredMixin, ListView):
    """
    Results of a search, natch.

    Also used to display the INVENTORY.
    """
    permission_required = ("lost_and_found.view_item",)
    model = Item
    paginate_by = 10

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context["jump_form"] = JumpForm()
        if "status" in context:
            context["status"] = self.kwargs["status"]
            context["body_bg"] = context["status"]
            context["new_url"] = reverse("lost_and_found:new", kwargs={"status": context["status"]})
        context["jump_form"] = JumpForm()
        return context

    def get_queryset(self) -> QuerySet[Any]:
        q = Item.objects.filter(convention=self.request.GET.get('convention'))
        if "categories" in self.request.GET:
            q = q.filter(category__in=self.request.GET.getlist('categories') or [])
        if "keywords" in self.request.GET and self.request.GET.get("keywords") != "":
            vector = SearchVector('description', 'details')
            query = self.__format_search(self.request.GET.get("search_type"))
            q = q.annotate(search=vector) \
                 .filter(search=query)
        return q

    def __format_search(self, human_type: str | None) -> SearchQuery | None:
        if human_type is None:
            human_type = "any"

        words = self.request.GET.get("keywords", "")

        if human_type == "any":
            words = " OR ".join(words.split())
            search_type = "websearch"
        elif human_type == "all":
            search_type = "plain"
        elif human_type == "phrase":
            search_type = "phrase"
        else:
            search_type = "websearch"

        return SearchQuery(words, search_type=search_type)


class InventoryView(SearchResultsView):
    permission_required = ("lost_and_found.can_inventory",)
    model = Item
    paginate_by = 10

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context["jump_form"] = JumpForm()
        context["body_bg"] = "inventoried"
        self.request.session["inventory"] = True
        context["inventory"] = self.request.session.get("inventory", False)
        return context

    def get_queryset(self) -> QuerySet[Any]:
        q = Item.objects.filter(convention=self.request.GET.get('convention') or Convention.current,
                                found=True, returned=False)
        return q



class ItemView(PermissionRequiredMixin, DetailView):
    """
    An individual LFI item, color-coded for status in the following priority order:
    missing (yellow)
    found (green)
    returned (blue)
    inventoried (purple)
    """
    permission_required = ("lost_and_found.view_item",)
    model = Item

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context["jump_form"] = JumpForm()
        context["inventory"] = self.request.session.get("inventory", False)
        context["status"] = context["item"].status
        context["body_bg"] = context["status"]
        return context


class ItemFormView(PermissionRequiredMixin, ModelFormMixin):
    model = Item

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context["jump_form"] = JumpForm()
        context["status"] = self.object.status if self.object is not None else self.kwargs["status"]
        context["body_bg"] = context["status"]
        return context

    def get_form(self, form_class: Type[BaseModelForm] | None = None) -> BaseModelForm:
        form = super().get_form(form_class)
        return form

    @property
    def fields(self) -> list:
        fields = ["category", "description", "found", "missing", "returned", "inventoried"]
        if self.missing:
            fields += ["where_last_seen", "owner_name", "owner_contact"]
        if self.found:
            fields += ["where_found"]
        if self.returned:
            fields += ["who_claimed"]

        fields += ["details"]
        return fields

    @property
    def missing(self) -> bool:
        return ("status" in self.kwargs and self.kwargs["status"] == "missing") or \
               (self.object and self.object.missing)

    @property
    def found(self) -> bool:
        return ("status" in self.kwargs and self.kwargs["status"] == "found") or \
               (self.object and self.object.found)

    @property
    def returned(self) -> bool:
        return ("status" in self.kwargs and self.kwargs["status"] == "returned") or \
               (self.object and self.object.returned)

    @property
    def inventoried(self) -> bool:
        return ("status" in self.kwargs and self.kwargs["status"] == "inventoried") or \
               (self.object and self.object.returned)


class NewItemView(ItemFormView, CreateView):
    """
    Create an item. Displayed fields depend on whether we're creating a MISSING or FOUND report.
    """
    permission_required = ("lost_and_found.add_item",)

    @property
    def success_url(self) -> str:
        return reverse_lazy("lost_and_found:detail", kwargs={"pk": self.object.pk})

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)
        if self.missing:
            context["form"].fields["missing"].initial = True
        if self.found:
            context["form"].fields["found"].initial = True

        return context

    def form_valid(self, form: BaseModelForm) -> HttpResponse:
        form.instance.convention = Convention.current
        form.instance.user = self.request.user
        return super().form_valid(form)


class UpdateItemView(ItemFormView, UpdateView):
    """
    Update an item.

    Usually only happens to update status (a missing item was found; a found
    item was returned, or inventoried.).
    """
    permission_required = ("lost_and_found.change_item",)

    def __init__(self, **kwargs: Any) -> None:
        self.object = None
        super().__init__(**kwargs)

    @property
    def success_url(self) -> str:
        return reverse_lazy("lost_and_found:detail", kwargs={"pk": self.kwargs["pk"]})

    def get(self, request: HttpRequest, *args: str, **kwargs: Any) -> HttpResponse:
        self.object = self.get_object()

        if "found" in request.GET:
            self.object.found = request.GET["found"]
        if "returned" in request.GET:
            self.object.returned = request.GET["returned"]
        if "inventoried" in request.GET:
            self.object.inventoried = request.GET["inventoried"]

        context = self.get_context_data()
        return self.render_to_response(context)

lost_and_found/templates/lost_and_found/_search_form.html
{% load bootstrap5 %}

{% bootstrap_field form.convention %}

{% bootstrap_field form.keywords %}
{% bootstrap_field form.search_type %}

lost_and_found/templates/lost_and_found/_sidebar.html
{% load bootstrap5 %}

<div class="row">
  <div class="col">
    <div class="card">
      <div class="card-header">
        <h5 class="card-title">Jump To Item</h5>
      </div>
      <div class="card-body">
        <form>
          {% bootstrap_form jump_form %}
        </form>
      </div>
    </div>

    <div class="card">
      <div class="card-body">
        <a class="btn btn-primary" href="{% url 'lost_and_found:index' %}">
          Lost and Found Home
        </a>
        {% if perms.lost_and_found.can_inventory %}
          {% if not inventory %}
          <a class="btn btn-inventoried btn-default" href="{% url 'lost_and_found:inventory' %}">
            Inventory Mode
          </a>
          {% else %}
          <a class="btn btn-inventoried btn-defult" href="{% url 'lost_and_found:index' %}">
            Exit Inventory Mode
          </a>
          {% endif %}
        {% endif %}
      </div>
    </div>

  </div>
</div>

lost_and_found/templates/lost_and_found/index.html
{% extends "base/layout.html" %}
{% load bootstrap5 %}
{% load bootstrap_icons %}
{% load static %}

{% block more-css %}
<link rel="stylesheet" type="text/x-scss" href="{% static 'lost_and_found/lost_and_found.scss' %}" />
{% endblock %}

<!-- Item jump sidebar here -->
{% block left_side %}
{% include "lost_and_found/_sidebar.html" %}
{% endblock %}

{% block content %}
<div class="card">
  <div class="card-header">
    <div class="card-title">
      Instructions
    </div>
  </div>
  <div class="card-body">
    <ul>
      <li>Choose your path! Is someone reporting an item they no longer have (Missing), or an item they've found (Found)</li>
      <li>Search to see if it's already been reported!</li>
      <li>Only if it has not been reported, create a new item!</li>
    </ul>
  </div>
</div>

<div class="row mt-3 lost-and-found-chooser">
  <div class="col-md-6">
    <div class="card missing">
      <div class="card-body">
        <a class="btn btn-lg"
                href="{% url 'lost_and_found:search' status='missing' %}">
          Missing Item
       </a>
        <div>I do not have the item in my hand</div>
      </div>
    </div>
  </div>

  <div class="col-md-6">
    <div class="card found">
      <div class="card-body">
        <a class="btn btn-lg"
                href="{% url 'lost_and_found:search' status='found' %}">
          Found Item
        </a>
        <div>I have the item in my hand</div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

lost_and_found/templates/lost_and_found/item_detail.html
{% extends "base/layout.html" %}
{% load bootstrap5 %}
{% load static %}

{% block more-css %}
<link rel="stylesheet" type="text/x-scss" href="{% static 'lost_and_found/lost_and_found.scss' %}" />
{% endblock %}

{% block left_side %}
{% include "lost_and_found/_sidebar.html" %}
{% endblock %}

{% block content %}
<div class="row">
  <div class="col-12">
    <h2>{{ item.status | capfirst }} Item</h2>

    <a class="btn btn-primary"
       href="{% url 'lost_and_found:edit' item.id %}">
      Edit Details
    </a>

    <div class="card">
      <div class="card-header {{body_bg}}">
        <div class="row">
          <div class="col">Item ID: {{item.id}}</div>
          <div class="col">Category: {{item.category}}</div>
          <div class="col">Updated at {{item.modified}}
            {% if item.user %}
            by {{item.user.name}}
            {% endif %}
          </div>
        </div>
      </div>
      <div class="card-body">
        <div><strong>Description:</strong> {{item.description}}</div>
        {% if item.missing %}
        <div><strong>Where Last Seen:</strong> {{item.where_last_seen}}</div>
        <div><strong>Owner Name: </strong> {{item.owner_name}}</div>
        <div><strong>Owner Contact:</strong> {{item.owner_contact}}</div>
        {% endif %}
        {% if item.found %}
        <div><strong>Where Found:</strong> {{item.where_found}}</div>
        {% endif %}
        {% if item.returned %}
        <div><strong>Claimed by:</strong> {{item.who_claimed}}</div>
        {% endif %}
        <div><strong>Details:</strong></div>
        <div>{{item.details}}</div>
      </div>
    </div>
  </div>
  <div class="row">
    <form action="{% url 'lost_and_found:edit' item.pk %}" class="found">
    {% if not item.returned %}
      {% if item.missing and not item.found %}
        <input type="hidden" name="found" value="True" />
        <input class="btn btn-found btn-default col" type="submit" value="Item Has Been Found" />
      {% endif %}

      {% if item.inventoried %}
        {% if inventory %}
          <a class="btn btn-inventoried btn-default col" href="{% url 'lost_and_found:inventory' %}">
            Return to Inventory
          </a>
        {% else %}
          <a class="btn btn-default col" href="javascript:history.back()">
            Back
          </a>
        {% endif %}
      {% endif %}

      {% if item.found and not inventory %}
        <input type="hidden" name="returned" value="True" />
        <input class="btn btn-returned btn-default col" type="submit" value="Item Has Been Returned" />
      {% endif %}

      {% if item.found and not item.inventoried and inventory %}
        <input type="hidden" name="inventoried" value="True" />
        <input class="btn btn-inventoried btn-default col" type="submit" value="Item Has Been Inventoried" />
      {% endif %}
    {% endif %}
  </div>
</div>
{% endblock %}

lost_and_found/templates/lost_and_found/item_form.html
{% extends "base/layout.html" %}
{% load bootstrap5 %}
{% load static %}

{% block more-css %}
<link rel="stylesheet" type="text/x-scss" href="{% static 'lost_and_found/lost_and_found.scss' %}" />
{% endblock %}

{% block left_side %}
{% include "lost_and_found/_sidebar.html" %}
{% endblock %}

{% block content %}
<div class="row">
  <div class="col">
    <form method="post">
      {% csrf_token %}
      {% bootstrap_field form.category %}
      {% bootstrap_field form.description %}

      {% if status == "missing" %}
      {% bootstrap_field form.where_last_seen %}
      {% bootstrap_field form.owner_name %}
      {% bootstrap_field form.owner_contact%}
      {% endif %}

      {% if status == "found" or status == "returned" %}
      {% bootstrap_field form.where_found %}
      {% endif %}

      {% if status == "returned" %}
      {% bootstrap_field form.who_claimed %}
      {% endif %}

      {% bootstrap_field form.details %}

      <input name="found" type="hidden" value="{{form.found.value}}" />
      <input name="missing" type="hidden" value="{{form.missing.value}}" />
      <input name="returned" type="hidden" value="{{form.returned.value}}" />
      <input name="inventoried" type="hidden" value="{{form.inventoried.value}}" />

      {% buttons %}
      <input class="btn btn-primary" type="submit" value="Save" />
      {% endbuttons %}
    </form>
  </div>
</div>
{% endblock %}

lost_and_found/templates/lost_and_found/item_list.html
{% extends "base/layout.html" %}
{% load bootstrap5 %}
{% load static %}

{% block more-css %}
<link rel="stylesheet" type="text/x-scss" href="{% static 'lost_and_found/lost_and_found.scss' %}" />
{% endblock %}

{% block left_side %}
{% include "lost_and_found/_sidebar.html" %}
{% endblock %}

{% block content %}
<div class="row">
  <div class="col">
    {% bootstrap_pagination page_obj %}

    {% if inventory %}
    <h1>INVENTORY IS FOR LLAMAS</h1>
    {% else %}
    <h1>LLAMAS ARE FOR {{inventory}}</h1>
    {% endif %}

    <div class="table-responsive">
      <table class="table table-hover">
        <thead>
          <tr>
            <th>ID</th>
            <th>Category</th>
            <th>Status</th>
            <th>Description</th>
          </tr>
        </thead>
        <tbody>
          {% for item in object_list %}
            <tr class="{{item.status}}"
                onclick="window.location = '{% url 'lost_and_found:detail' item.id %}'">
              <td>{{item.id}}</td>
              <td>{{item.category.name}}</td>
              <td>{{item.status | upper}}</td>
              <td>{{item.description}}</td>
            </tr>
          {% endfor %}
      </table>
    </div>

    <div>
      <a class="btn" href={{new_url}}>Create New Item</a>
    </div>
  </div>
</div>

{% endblock %}

lost_and_found/templates/lost_and_found/search.html
{% extends "base/layout.html" %}
{% load bootstrap5 %}
{% load static %}

{% block more-css %}
<link rel="stylesheet" type="text/x-scss" href="{% static 'lost_and_found/lost_and_found.scss' %}" />
{% endblock %}

{% block left_side %}
{% include "lost_and_found/_sidebar.html" %}
{% endblock %}

{% block content %}
<div class="row">
  <h1>Search for an item</h1>
  <div class="col">
    <form method="post" class="form-horizontal">
      {% csrf_token %}
      {{ form }}
      {% buttons %}
      <input class="btn btn-primary" type="submit" value="Search" />
      {% endbuttons %}
    </form>
  </div>
</div>
{% endblock %}