base/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('banner', views.BannerView.as_view(), name='banner')
]

cononaplane/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('base.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
    path('log/', include('log.urls',  namespace='log')),
    path('lost_and_found/', include('lost_and_found.urls', namespace="lost_and_found")),
]

log/urls.py
from django.urls import path

from . import views

app_name = 'log'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index', kwargs={"status": "active"}),
    path('<str:status>', views.IndexView.as_view(), name='index'),
    path('threads', views.ThreadsView.as_view(), name='threads', kwargs={"status": "active"}),
    path('threads/<int:pk>', views.ThreadDetailView.as_view(), name="show"),
    path('threads/<str:status>', views.ThreadsView.as_view(), name='threads'),
    path('entries/new', views.ThreadFormView.as_view(), name='create'),
    path('entries/<int:pk>/update', views.ThreadFormView.as_view(), name='update')
]

base/models.py
"""
Models for the base app
"""
from datetime import date
from django.db import models
from django.forms import ValidationError


def user_role(user) -> str:
    """
    Return the user's current role. Not fully implemented, yet.
    Current:
    * If admin, say admin
    * If not a member of any group, return <no role>
    * Otherwise, return the first group on the list

    Intended:
    * Allow a user to specify at login what role they're fulfilling
      and store it in the session, refer to it here.
    """
    if user.is_superuser:
        return "admin"
    if user.groups.count() == 0:
        return "<no role>"

    return user.groups.all()[0].name


def date_range_validator(start: date, end: date) -> None:
    """
    No overlaps, no inclusions.
    """
    # end1 ≥ start2 and end2 ≥ start1
    query = Convention.objects.filter(end_date__gt=start, start_date__lte=end)
    if query.count() > 0:
        raise ValidationError(f"These dates {start}->{end} overlap with an existing"
                              f"convention {query}")


class Convention(models.Model):
    """
    Model representing a convention period.
    """
    name = models.CharField(max_length=100, db_index=True, unique=True)
    start_date = models.DateField(blank=False, db_index=True,
                                  help_text="""
                                  Inclusive--this should be the first day of the convention year.
                                  It may also be the same day as the previous year's end date.
                                  """)
    end_date = models.DateField(blank=False, db_index=True,
                                help_text="""
                                Exclusive--this should be the day AFTER the last
                                date of the convention year. It may also be the same day as
                                the next year's start date.
                                """)

    @classmethod
    @property
    def current(cls):
        """
        Return the current convention. If nothing matches the date, return
        the most recently held convention. If we haven't defined any conventions
        yet, return None
        """
        now = date.today()
        ret = None
        try:
            ret = Convention.objects.get(start_date__lte=now, end_date__gt=now)
        except cls.DoesNotExist:
            q = Convention.objects.filter(start_date__lte=now).order_by("-start_date")
            if len(q) > 0:
                ret = q[0]
            else:
                ret = None
        return ret

    def clean(self) -> None:
        date_range_validator(self.start_date, self.end_date)
        return super().clean()

    def __str__(self) -> str:
        return f"{self.name}: {self.start_date} -> {self.end_date}"

lost_and_found/models.py
from django.conf import settings
from django.contrib.postgres.indexes import GinIndex
from django.db import models

from model_utils.models import TimeStampedModel as TSModel
from simple_history.models import HistoricalRecords

from base.models import Convention


class Category(TSModel):
    name = models.CharField(max_length=60, unique=True)
    in_use = models.BooleanField(default=True)

    def __str__(self) -> str:
        if self.in_use:
            return self.name
        else:
            return f"{self.name} (not in use)"


class Item(TSModel):
    STATUSES = {"found", "inventoried", "missing", "returned"}
    found = models.BooleanField(default=False, db_index=True)
    inventoried = models.BooleanField(default=False, db_index=True)
    missing = models.BooleanField(default=False, db_index=True)
    returned = models.BooleanField(default=False, db_index=True)

    where_found = models.CharField(max_length=200, null=True, blank=True)
    where_last_seen = models.CharField(max_length=200, null=True, blank=True)

    description = models.CharField(max_length=200)
    details = models.TextField()

    owner_contact = models.CharField(max_length=200, null=True, blank=True)
    owner_name = models.CharField(max_length=200, null=True, blank=True)
    who_claimed = models.CharField(max_length=200, null=True, blank=True)

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING)
    rolename = models.CharField(max_length=25)

    category = models.ForeignKey(Category, on_delete=models.DO_NOTHING)
    convention = models.ForeignKey(Convention, on_delete=models.DO_NOTHING)

    history = HistoricalRecords()

    @property
    def status(self) -> str:
        if self.returned:
            return "returned"
        if self.inventoried:
            return "inventoried"
        if self.found:
            return "found"
        if self.missing:
            return "missing"
        return "WTH"

    @status.setter
    def status(self, val: str) -> str:
        if val == "returned":
            self.returned = True
        if val == "inventoried":
            self.inventoried = True
        if val == "found":
            self.found = True
        if val == "missing":
            self.missing = True
        return val

    def clean(self) -> None:
        return super().clean()

    class Meta:
        indexes = [
            GinIndex(fields=['description', 'details'])
        ]
        ordering = ["created"]
        permissions = [(
            "can_inventory",
            "Can perform inventory functions"
        )]

base/views.py
from typing import Any, Dict
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render
from django.views.generic import TemplateView

from log.models import Thread


@login_required
def index(request: HttpRequest) -> HttpResponse:
    response = render(request, 'base/index.html')
    return response


class BannerView(LoginRequiredMixin, TemplateView):
    template_name = 'base/_banner.html'

    def get_context_data(self, **kwargs) -> Dict[str, Any]:
        context: Dict[str, Any] = super().get_context_data(**kwargs)
        context['active_count'] = Thread.objects.filter(status='active').count()
        context['emergency_count'] = Thread.objects.filter(status='active', emergency=True).count()
        context['medical_count'] = Thread.objects.filter(status='active', medical=True).count()

        context['background_class'] = self.__get_background_class(context)
        return context

    def get(self, request, *args, **kwargs) -> HttpResponse:
        return super().get(request, args, kwargs)

    def __get_background_class(self, context: dict) -> str:
        """
        Priority is:
            * Emergency or medical: class is emergency
            * Active issues: class is is_active (avoiding collision with Bootstrap)
            * Else: no class (default)
        """
        if context['emergency_count'] > 0 or \
           context['medical_count'] > 0:
            return 'emergency'
        elif context['active_count'] > 0:
            return 'is_active'
        else:
            return ''

base/templates/base/_banner.html
{% load static %}
<div class="{{ background_class }} banner ">
  <div class="row">
    <div class="col-2">
      <img class="logo" src="{% static 'base/ciab-logo-trans.png' %}" />
    </div>
    <div class="col">
      <div>{{ active_count }} Active Issue{{ active_count|pluralize:"s" }} (exc. sticky/secure)</div>
      <div>{% now 'd E Y H:i:s e' %}&mdash;User: {{ user }}</div>
    </div>
    <div class="col">
      <div>{{ emergency_count }} Emergenc{{ emergency_count|pluralize:"y,ies" }}
      <div>{{ medical_count }} Medical Issue{{ medical_count|pluralize:"s" }}
    </div>
  </div>
</div>

base/templates/base/_login_banner.html
{% load static %}
{% block banner %}
  <div class="banner">
    <div class="row">
      <div class="col">
        <img class="logo" src="{% static 'ciab-logo-trans.png' %}" />
      </div>
      <div class="col">
        <h1>Con On a Plane</h1>
      </div>
    </div>
  </div>
{% endblock %}

base/templates/base/index.html
{% extends 'base/layout.html' %}
{% load bootstrap5 %}
{% block content %}

<blockquote class="blockquote">
  <p>The Doctor: It says "Dig hole here!"</p>

  <p>Ace: What does it say that in?</p>

  <p>The Doctor: My handwriting! Ace, we need a hole!</p>
</blockquote>

{% endblock %}

base/templates/base/layout.html
{% load compress %}
{% load static %}
{% load bootstrap5 %}
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />

  <title>ConOnAPlane | {% block title %}{% endblock %}</title>

  <script src="https://unpkg.com/hyperscript.org@0.9.7"></script>
  <script src="https://unpkg.com/htmx.org@1.9.6"></script>
  <script src="https://unpkg.com/idiomorph/dist/idiomorph-ext.min.js"></script>
  <script src="https://unpkg.com/htmx.org/dist/ext/ajax-header.js"></script>
  <script src="https://unpkg.com/htmx.org/dist/ext/debug.js"></script>
  <script src="https://unpkg.com/@popperjs/core@2"></script>
  {% bootstrap_javascript %}
  {% bootstrap_css %}
  {% compress css %}
    <link rel="stylesheet" type="text/x-scss" href="{% static 'base/app.scss' %}" />
    {% block more-css %}
    {% endblock %}
  {% endcompress %}

  <script type="text/javascript">
    document.addEventListener("DOMContentLoaded", function() {
      var tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]'))
      var tooltipList = tooltipTriggerList.map(function (tooltipTriggerEl) {
        return new bootstrap.Tooltip(tooltipTriggerEl)
      });
      var popoverTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="popover"]'))
      var popoverList = popoverTriggerList.map(function (popoverTriggerEl) {
        console.log("SQUONK");
        return new bootstrap.Popover(popoverTriggerEl)
      });
    });
  </script>
</head>

<body
  hx-ext="ajax-header"
  hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'
  >

  <script>
      document.body.addEventListener('htmx:configRequest', (event) => {
        event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}';
      })
  </script>

  {% block banner %}
    <div class="container-fluid">
      <div class="row">
        <div class="col">
          {% if user.is_authenticated %}
            <div id="banner"
                hx-ext="morph"
                hx-ext="debug"
                hx-get="/banner"
                hx-trigger="load, every 30s"
                hx-swap="morph:innerHTML"
                hx-target="#banner">
              {% include 'base/_banner.html' %}
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  {% endblock %}

  {% block nav %}
    <div class="container-fluid">
      {% autoescape off %}
        {% bootstrap_messages %}
      {% endautoescape %}

      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="/log/">Main</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/log/entries/new">Log Event</a>
              </li>
              {% if perms.lost_and_found.view_item %}
              <li class="nav-item">
                <a class="nav-link" href="/lost_and_found">Lost/Found</a>
              </li>
              {% endif %}
              {% if user.is_staff %}
              <li class="nav-item">
                <a class="nav-link" href="/admin">Admin</a>
              </li>
              {% endif %}
              <li class="nav-item">
                <a class="nav-link" href="/accounts/logout">Logout</a>
              </li>
            {% else %}
              <li class="nav-item">
                <a class="nav-link" aria-current="page" href="/accounts/login/?next=/">Log In</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/accounts/signup/?next=/accounts/login">Sign up</a>
              </li>
            {% endif %}
            </ul>
        </div>
      </nav>
    </div>
  {% endblock %}

  <div class="container-fluid {{body_bg}}" hx-ext="morph">
    <div class="row">
      <div class="col-md-3" id="left_side">{% block left_side %}{% endblock %}</div>
      <div class="col" id="content">{% block content %}{% endblock %}</div>
    </div>
  </div>

  {% block indicia %}
    <div class="container {{ body_bg }}">
      <div class="row">
        <div class="col">
          <hr />
          <p class="text-center fs-6 fw-light"><a href="https://gitlab.com/cononaplane/cononaplane">ConOnAPlane</a> Copyright &copy; 2023 Michael Scott Shappe. See <a href="https://gitlab.com/cononaplane/cononaplane/LICENSE.md">the MIT Licence</a>.</p>
        </div>
      </div>
    </div>
  {% endblock %}

</body>

</html>