cononaplane/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('base.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
    path('log/', include('log.urls',  namespace='log')),
    path('lost_and_found/', include('lost_and_found.urls', namespace="lost_and_found")),
]

log/urls.py
from django.urls import path

from . import views

app_name = 'log'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index', kwargs={"status": "active"}),
    path('<str:status>', views.IndexView.as_view(), name='index'),
    path('threads', views.ThreadsView.as_view(), name='threads', kwargs={"status": "active"}),
    path('threads/<int:pk>', views.ThreadDetailView.as_view(), name="show"),
    path('threads/<str:status>', views.ThreadsView.as_view(), name='threads'),
    path('entries/new', views.ThreadFormView.as_view(), name='create'),
    path('entries/<int:pk>/update', views.ThreadFormView.as_view(), name='update')
]

log/models.py
from django.conf import settings
from django.db import models
from django.contrib.postgres.indexes import GinIndex

from model_utils import Choices
from model_utils.fields import MonitorField, StatusField
from model_utils.models import TimeStampedModel as TSModel
from simple_history.models import HistoricalRecords

from base.models import Convention
from departments.models import Department


class EntryStatusBase(models.Model):
    STATUS = Choices('active', 'sticky', 'closed')

    class Meta:
        abstract = True


class Thread(TSModel, EntryStatusBase):
    departments = models.ManyToManyField(Department, db_index=True)
    convention = models.ForeignKey(Convention, on_delete=models.CASCADE)

    emergency = models.BooleanField(db_index=True, default=False)
    medical = models.BooleanField(db_index=True, default=False)
    post_con = models.BooleanField(db_index=True, default=False)
    status = StatusField()
    status_changed = MonitorField(monitor='status')  # type: ignore Pylance doesn't like model_utils

    history = HistoricalRecords(m2m_fields=[departments], bases=[EntryStatusBase])

    @property
    def status_icon(self) -> str:
        ret = ''
        if self.medical:
            ret = 'plus-circle-fill'
        elif self.emergency:
            ret = 'exclamation-octagon-fill'
        elif self.status == 'active':
            ret = 'lightning-fill'
        elif self.status == 'sticky':
            ret = 'sticky-fill'

        return ret

    @property
    def status_for_header(self) -> str:
        ret: str = f"{self.status.capitalize()} "
        for flag in {'emergency', 'medical', 'post_con'}:
            if self.__getattribute__(flag):
                ret += f"{flag.capitalize()} "

        return ret

    @property
    def status_class(self) -> str:
        ret = ''
        if self.medical or self.emergency:
            ret = 'emergency'
        elif self.status == 'active':
            ret = 'is_active'
        elif self.status == 'sticky':
            ret = "sticky"

        return ret

    @property
    def departments_for_header(self) -> str:
        return ', '.join({dept.name for dept in self.departments.all()})

    class Meta:
        ordering = ['-created']


class Entry(TSModel, EntryStatusBase):
    """
    An Entry represents an incident in the log. Entries belong to Threads, which
    hold state. State history is handled by HistoricalRecords and not currently displayed.
    """
    thread = models.ForeignKey(Thread, on_delete=models.DO_NOTHING)

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING)
    rolename = models.CharField(max_length=25)

    description = models.TextField(help_text="""
                                   Describe the current state of the issue.
                                   Avoid any and all Personally Identifiable Information,
                                   including
                                   <ul>
                                    <li>Names</li>
                                    <li>Badge Names</li>
                                    <li>Badge Numbers</li>
                                   </ul>
                                   """)

    secure_information = models.TextField(help_text="""
                                          Use this field to add any sensitive or
                                          Personally Identifiable Information, health information,
                                          etc. Depending on your role, you may not be
                                          able to see this information once you've entered it.
                                          """,
                                          blank=True)

    class Meta:
        indexes = [
            GinIndex(fields=['description'])
        ]
        ordering = ['-created']
        permissions = [('can_read_secure_information', 'Can read secure information')]

log/forms.py
from typing import Any, Dict, Type

from django.forms import CheckboxSelectMultiple, Form, ModelForm, IntegerField

from .models import Entry, Thread


class ThreadForm(ModelForm):
    class Meta:
        model: Type = Thread
        fields: list = [
            'status',
            'departments',
            'emergency',
            'medical',
            'post_con',
        ]
        widgets: dict = {
            'departments': CheckboxSelectMultiple
        }


class EntryForm(ModelForm):
    class Meta:
        model: Type = Entry
        fields: list = [
            'description',
            'secure_information'
        ]


class JumpForm(Form):
    jump = IntegerField(min_value=1)

    def clean(self) -> Dict[str, Any]:
        cleaned_data = super().clean()
        pk = cleaned_data.get('jump')

        if pk:
            try:
                Thread.objects.get(pk=pk)
            except Thread.DoesNotExist:
                self.add_error('jump', 'No such thread')
        return cleaned_data

log/views.py
from typing import Any, Dict, List, Set, Type

from django.contrib.auth.mixins import PermissionRequiredMixin
from django.db import models, transaction
from django.http import HttpRequest, HttpResponse, QueryDict
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views.generic import TemplateView, ListView, DetailView
from base.models import Convention

from departments.models import Department
from .forms import EntryForm, JumpForm, ThreadForm
from .models import Entry, EntryStatusBase, Thread


class BaseThreadsView(ListView):
    model: Type = Thread
    active_url: str = reverse_lazy("log:threads")
    paginate_by: int = 10
    prefetcher = models.Prefetch('entry_set', queryset=Entry.objects.order_by('-created'))

    def get(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse:
        if "jump" in request.GET:
            return redirect(reverse_lazy('log:show', args=(request.GET['jump'],)))
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs) -> Dict[str, Any]:
        switch_to = "sticky" if self.status != "sticky" else "active"
        context:  Dict[str, Any] = super().get_context_data(**kwargs)
        context["refresh_url"] = f"{reverse_lazy('log:threads', args=(self.status,))}?page={self.page}"
        context["switcher_url"] = reverse_lazy("log:index", args=(switch_to,))
        context["switch_to"] = switch_to
        context['jump_form'] = JumpForm()
        context['possible_departments'] = Department.objects.filter(pk__in=Department.for_user(self.request.user))
        context['selected_departments'] = self.selected_departments
        context['possible_cons'] = Convention.objects.order_by("-start_date")
        context['selected_convention'] = self.selected_convention.pk
        if self.request.GET.get('keywords'):
            context['keywords'] = self.request.GET.get('keywords')
        context['include_closed'] = self.request.GET.get('include-closed')
        return context

    def get_queryset(self) -> models.QuerySet:
        q = Thread.objects.filter(convention=self.selected_convention,
                                  departments__in=self.selected_departments,
                                  departments__has_log=True)
        if self.request.GET.get('include-closed'):
            q = q.filter(status__in=(self.status, 'closed'))
        else:
            q = q.filter(status=self.status)

        if self.request.GET.get('keywords'):
            q = q.filter(entry__description__search=self.request.GET.get('keywords'))
        return q.prefetch_related(self.prefetcher) \
                .distinct() \
                .order_by('-entry__created')

    # String interpolation can't be done lazy -- it will be done before Django knows its
    # URLs if we define this as a class-level variable like we're supposed to. Fortunately,
    # we can be tricky....
    @property
    def login_url(self):
        return f"{reverse_lazy('login')}?={reverse_lazy('log:threads')}"

    @property
    def status(self) -> str:
        if self.kwargs["status"] in EntryStatusBase.STATUS:
            return self.kwargs["status"]

        return "active"

    @property
    def selected_departments(self) -> Set[int] | None:
        if 'selected_departments' not in self.request.session:
            return Department.for_user(self.request.user)  # [dept.id for dept in self.request.user.d.all()]
        return {int(x) for x in self.request.session['selected_departments']}

    @selected_departments.setter
    def selected_departments(self, value: List[int | str] | Set[int | str] = set()) -> Set[int | str] | None:
        self.request.session['selected_departments'] = value
        return set(value)

    @property
    def selected_convention(self) -> Convention:
        if 'selected_convention' not in self.request.session:
            return Convention.current
        else:
            return Convention.objects.get(pk=int(self.request.session['selected_convention']))

    @selected_convention.setter
    def selected_convention(self, value: int) -> int:
        self.request.session['selected_convention'] = value
        return value

    @property
    def page(self) -> int:
        return int(self.request.GET.get('page') or 1)


class IndexView(PermissionRequiredMixin, BaseThreadsView):
    template_name: str = 'log/index.html'
    permission_required = ("log.view_thread",)
    paginate_by: int = 10

    def post(self, request: HttpRequest, *args, **kwargs) -> HttpResponse:
        if 'dept-select' in request.POST:
            depts: List = request.POST.getlist('dept-select')
            self.selected_departments = [int(x) for x in depts]

        if 'convention' in request.POST:
            con: int = int(request.POST.get('convention') or '0')
            self.selected_convention = con

        redir = reverse_lazy("log:index")
        query = dict()
        if 'keywords' in request.POST and request.POST.get('keywords') and request.POST.get('keywords') != 'None':
            query['keywords'] = request.POST.get('keywords')
        if 'include-closed' in request.POST:
            query['include-closed'] = 'on'
        qd = QueryDict(mutable=True)
        qd.update(query)
        return redirect(redir + "?" + qd.urlencode())


class ThreadsView(PermissionRequiredMixin, BaseThreadsView):
    template_name: str = 'log/_threads.html'
    permission_required = ("log.view_thread",)
    paginate_by: int = 10


class ThreadDetailView(PermissionRequiredMixin, DetailView):
    model: Type = Thread
    prefetcher = models.Prefetch('entry_set', queryset=Entry.objects.order_by('-created'))
    template_name: str = "log/thread.html"
    permission_required = ("log.view_thread",)

    def get_context_data(self, **kwargs) -> Dict[str, Any]:
        context: Dict[str, Any] = super().get_context_data(**kwargs)
        context['detail'] = True
        return context


class ThreadFormView(PermissionRequiredMixin, TemplateView):
    template_name: str = "log/entry_form.html"
    permission_required = ("log.view_thread", "log.add_thread", "log.view_entry", "log.add_entry")

    def setup(self, request, *args, **kwargs) -> None:
        self.thread: Thread | None = Thread.objects.get(pk=kwargs['pk']) \
            if 'pk' in kwargs else None
        super().setup(request, *args, **kwargs)

    def get_context_data(self, **kwargs) -> Dict[str, Any]:
        context: Dict[str, Any] = super().get_context_data(**kwargs)
        context['thread_form'] = ThreadForm(prefix='flags', instance=self.thread)
        context['form'] = EntryForm(prefix='entry')
        context['no_update_button'] = self.thread is not None

        if self.thread:
            context['thread'] = self.thread

        return context

    def post(self, request: HttpRequest, *args, **kwargs) -> HttpResponse:
        with transaction.atomic():
            thread_form = ThreadForm(request.POST, prefix='flags', instance=self.thread)
            entry_form = EntryForm(request.POST, prefix='entry')

            if thread_form.is_valid() and entry_form.is_valid():
                if not thread_form.instance.convention_id:
                    thread_form.instance.convention = Convention.current
                thread_form.save()
                entry_form.instance.user = self.request.user
                entry_form.instance.rolename = 'nothing yet'
                entry_form.instance.thread = thread_form.instance
                entry_form.save()
                return redirect(to=self.success_url(thread_form.instance.status))
            else:
                return render(request, self.template_name,
                              {'form': entry_form, 'thread_form': thread_form})

    def success_url(self, status) -> str:
        if status not in ('active', 'sticky'):
            status = 'active'

        return reverse_lazy("log:index", args=(status, ))

log/templates/log/_entry.html
<li class="entry" id="entry-{{ entry.pk }}">
  <div class="entry_metadata">
    <div class="date">{{ entry.created }}</div>
    <div class="volunteer">entered by {{ entry.user.realname }} ({{ entry.user }}) as {{ entry.rolename }}</div>
  </div>
  <div class="description">
    {{ entry.description|linebreaks }}
  </div>
  {% if entry.secure_information %}
    {% if not perms.log.can_read_secure_information %}
      <div class="bg-warning">This entry includes secure information</div>
    {% else %}
      <div>
        {% if not detail %}
          <button class="btn-warning">
            <a href="{% url 'log:show' pk=thread.pk %}">This entry includes secure information. Click to view on a separate page.</a>
          </button>
        {% else %}
          <div class="card">
            <div class="card-header bg-warning">
              <h3>Secure information</h3>
            </div>
            <div class="card-body">
              {{ entry.secure_information }}
            </div>
          </div>
        {% endif %}
      </div>
    {% endif %}
  {% endif %}
</li>

log/templates/log/_no_refresh.html
<div class="card">
  <div class="card-body bg-warning">
    <div>NOTE: This page does <strong>not</strong> auto-refresh</div>
    <div>Return to <a href="{% url 'log:index' status='active' %}">active log view</a></div>
  </div>
</div>

log/templates/log/_thread.html
<div class="thread" id="thread-{{ thread.pk }}">
  <div class="row">
    <div class="col">
      <div class="card">
        <div class="card-header">
          {% include "log/_thread_metadata.html" %}
        </div>
        <div class="card-body">
          <ul class="entries">
            {% for entry in thread.entry_set.all %}
              {% include "log/_entry.html" %}
            {% endfor %}
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

log/templates/log/_thread_metadata.html
{% load bootstrap_icons %}

<div class="row thread-metadata">
  <div class="col">
    {% if not no_update_button %}
      <a class="btn btn-primary" href="{% url 'log:update' pk=thread.pk %}">Update Event</a>
    {% endif %}
  </div>
  <div class="col">
    <div class="thread-metadata {{thread.status_class}}">{% bs_icon thread.status_icon %} {{ thread.status_for_header }}</div>
    <div>{{ thread.departments_for_header }}</div>
  </div>
  <div class="col">
    <div class="text-end"><strong>ID: <a href="{% url 'log:show' pk=thread.pk %}">{{ thread.pk }}</strong></a></div>
  </div>
</div>

log/templates/log/_threads.html
{% load bootstrap5 %}
{% bootstrap_pagination page_obj %}
{% for thread in object_list %}
  {% include 'log/_thread.html' %}
{% endfor %}

log/templates/log/entry_form.html
{% extends 'base/layout.html' %}
{% load bootstrap5 %}

{% block content %}
{% if thread %}
<h1>Update a thread</h1>
{% else %}
<h1>Start a new thread</h1>
{% endif %}

<form method="post" role="form">
  {% csrf_token %}

  <div class="row">
    <div class="col">
      {% bootstrap_form form %}
    </div>

    <div class="col-3">
      {% bootstrap_field thread_form.status %}
      <hr />
      {% bootstrap_field thread_form.emergency %}
      {% bootstrap_field thread_form.medical %}
      {% bootstrap_field thread_form.post_con %}
      <hr />
      {% bootstrap_field thread_form.departments %}
    </div>
  </div>


  {% buttons %}
  <input class="btn btn-primary" type="submit" value="Save" />
  {% endbuttons %}
</form>

{% if thread %}
<hr>

{% include 'log/_thread.html' %}
{% endif %}

{% endblock %}

log/templates/log/index.html
{% extends 'base/layout.html' %}
{% load bootstrap5 %}
{% load bootstrap_icons %}

{% block left_side %}
<div class="row">
  <div class="col">
    {% if keywords or include_closed %}
    {% include "log/_no_refresh.html" %}
    {% endif %}
    <div class="card">
      <div class="card-body" id="thread-view-switcher">
        Switch to <a href="{{ switcher_url }}">{{ switch_to|capfirst }}</a>
      </div>
    </div>
    <div class="card">
      <div class="card-header" id="searches-card">
        <h5 class="card-title">Searches<span data-bs-toggle="popover" data-bs-content="Jump takes a Thread ID. Keywords allows a text search of entries (but not secure information)." title="Searches Help">{% bs_icon "question-circle-fill" %} </span></h5>
      </div>
      <div class="card-body">
        <form>
          {% bootstrap_form jump_form %}
        </form>
      </div>
    </div>
    <div class="card">
      <div class="card-header" id="departments-card">
        <h5 class="card-title">
          Departments
          <span data-bs-toggle="popover" data-bs-content="By default, the log displays threads from all departments to which you belong, that have logs enabled. Select specific logs here." title="Departments Help">{% bs_icon "question-circle-fill" %}</span>
        </h5>
      </div>
      <div class="card-body">
        <form method="post">
          {% csrf_token %}
          {% for dept in possible_departments %}
          <div class="form-check">
            <input class="form-check-input" type="checkbox" name="dept-select" value="{{dept.id}}"
                   {% if dept.id in selected_departments %}checked{% endif %} />
            <label class="form-check-label" for="dept-select">{{dept.name}}</label>
          </div>
          {% endfor %}
          <button class="mt-3 btn btn-sm btn-success">Submit</button>
        </form>
      </div>
    </div>
    <div class="card">
      <div class="card-header" id="conventions-card">
        <h5 class="card-title">
          Keywords and Conventions
          <span data-bs-toggle="popover" data-bs-content="You can view past conventions by selecting them from the menu. You can search text in descriptions using the blank. You can search closed threads by checking 'Include Closed'" data-bs-title="Search Help">{% bs_icon "question-circle-fill"%}</span>
        </h5>
      </div>
      <div class="card-body">
        <form method="post">
          {% csrf_token %}
          <div>
            <label class="form-label" for="convention">Currently viewing</label>
            <select class="form-select" name="convention" id="convention">
              {% for con in possible_cons %}
                <option value="{{con.id}}"
                        {% if con.id == selected_convention %}selected{% endif %}>{{con.name}}</option>
              {% endfor %}
            </select>
          </div>
          <div class="mt-3">
            <label class="form-label" for="keywords">Search keywords</label>
            <input class="form-control" type="text" name="keywords" value="{{keywords}}" />
          </div>
          <div class="mt-3 form-check">
            <input class="form-check-input" type="checkbox" name="include-closed" value="{{include_closed}}"
                   {% if include_closed %}checked{% endif %} />
            <label class="form-check-label" for="include-closed">Include Closed?</label>
          </div>
          <button type="submit" class="mt-3 btn btn-sm btn-success">Submit</button>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}
{% block content %}
  <div id="threads"
       hx-get="{{ refresh_url }}"
       hx-target="#threads"
       {% if not keywords %}hx-trigger="every 30s"{% endif %}
       hx-swap="morph:innerHTML"
  >
  {% include 'log/_threads.html' %}
  </div>
{% endblock %}

log/templates/log/thread.html
{% extends 'base/layout.html' %}
{% load bootstrap5 %}

{% block left_side %}
{% include "log/_no_refresh.html" %}
{% endblock %}

{% block content %}
{% include "log/_thread.html" %}
{% endblock %}